import test from "node:test";
import assert from "node:assert/strict";
import { chromium, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { startServer } from "./server.mjs";
import { harness } from "./test-support.mjs";

test("canvas buttons provision, link, dispatch and expose the PR using fake GitHub and session adapters", async (t) => {
  const h = await harness(t);
  const server = await startServer(h.controller);
  t.after(server.close);
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 900, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(server.url);
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Show what Copilot can do.");
  await expect(page.getByRole("heading", { level: 3 })).toHaveCount(5);
  await expect(page.getByRole("heading", { name: "Copilot Autofix", exact: true })).toHaveCount(1);
  await expect(page.getByText("GITHUB ADVANCED SECURITY", { exact: true })).toHaveCount(1);
  await expect(page.getByRole("button", { name: "Run feature demo" })).toBeDisabled();
  await expect(page.getByRole("textbox")).toHaveCount(0);
  await expect(page.getByRole("checkbox")).toHaveCount(0);
  await page.getByRole("button", { name: "Create environment", exact: true }).click();
  await expect(page.getByTestId("repo-link")).toHaveText(/^presenter\/tailspin-demo-\d{4}-\d{2}-\d{2}-[a-f0-9]{8}$/);
  const { repo } = await h.current();
  await expect(page.getByTestId("open-autofix-pr")).toHaveAttribute("href", `https://github.com/${repo}/pull/1`);
  await expect(page.getByTestId("open-autofix-pr")).toHaveText("Open Copilot Autofix PR");
  await expect(page.getByRole("button", { name: "Run feature demo" })).toBeDisabled();
  assert.equal(h.messages.length, 1);
  await h.link();
  await expect(page.getByRole("button", { name: "Run feature demo" })).toBeEnabled();
  await page.getByRole("button", { name: "Check readiness" }).click();
  await expect(page.locator("#scan-status")).toContainText("Waiting for CodeQL");
  await page.getByTestId("prompt-summary").click();
  await expect(page.locator("#feature-prompt")).toContainText("case-insensitive filtering");
  await page.getByRole("button", { name: "Run feature demo" }).click();
  await expect(page.locator("#feature-status")).toContainText("Prompt queued");
  assert.equal(h.messages.length, 2);
  await page.reload();
  await expect(page.getByTestId("repo-link")).toHaveText(repo);
  await expect(page.getByRole("button", { name: "Run feature demo" })).toBeDisabled();
  await page.getByRole("button", { name: "Recover app session" }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(page.getByRole("button", { name: "Recover app session" })).toBeFocused();
  assert.equal(h.messages.length, 2);
  await page.setViewportSize({ width: 375, height: 900 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.emulateMedia({ colorScheme: "dark" });
  for (const theme of ["light", "dark"]) {
    await page.goto(`${server.url}?clawpilotTheme=${theme}`);
    await expect(page.getByTestId("repo-link")).toHaveText(repo);
    await expect(page.locator("html")).toHaveAttribute("data-theme", theme);
    await expect(page.locator("body")).toHaveCSS("background-color", theme === "light" ? "rgb(255, 255, 255)" : "rgb(13, 17, 23)");
    const results = await new AxeBuilder({ page }).analyze();
    assert.deepEqual(results.violations.map(({ id, nodes }) => ({ id, targets: nodes.map((node) => node.target) })), [], `Accessibility in ${theme} theme`);
  }
  await page.goto(server.url);
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.emulateMedia({ colorScheme: "light" });
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light");
  await page.evaluate(() => {
    document.documentElement.dataset.colorMode = "dark";
    document.documentElement.style.setProperty("--background-color-default", "#151b23");
    document.documentElement.style.setProperty("--text-color-default", "#f0f6fc");
    document.documentElement.style.setProperty("--true-color-blue", "#79c0ff");
  });
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await expect(page.locator("body")).toHaveCSS("background-color", "rgb(21, 27, 35)");
  await expect(page.getByTestId("repo-link")).toHaveCSS("color", "rgb(121, 192, 255)");
  const hostedResults = await new AxeBuilder({ page }).analyze();
  assert.deepEqual(hostedResults.violations.map(({ id }) => id), [], "Accessibility with app theme tokens");
  await page.evaluate(() => {
    document.documentElement.removeAttribute("data-color-mode");
    document.documentElement.removeAttribute("style");
    document.body.dataset.colorMode = "dark";
  });
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.evaluate(() => { document.body.dataset.colorMode = "light"; });
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light");
  assert.deepEqual(errors, []);
});

test("new scenario controls launch issue work, request review, and gate repair on current failing CI", async (t) => {
  const h = await harness(t);
  await h.create();
  await h.link();
  const environment = await h.current();
  const server = await startServer(h.controller);
  t.after(server.close);
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(server.url);
  await expect(page.getByTestId("issue-link")).toHaveAttribute("href", `https://github.com/${environment.repo}/issues/${environment.scenarios.issue.number}`);
  await expect(page.getByTestId("review-link")).toHaveAttribute("href", `https://github.com/${environment.repo}/pull/${environment.scenarios.review.number}`);
  await expect(page.getByTestId("ci-link")).toHaveAttribute("href", `https://github.com/${environment.repo}/pull/${environment.scenarios.ci.number}`);
  await expect(page.getByTestId("run-ci")).toBeDisabled();
  await page.getByTestId("run-issue").click();
  await expect(page.locator("#issue-status")).toContainText("Handoff requested");
  assert.match(h.messages[1].prompt, /open_issue_session/);
  await expect(page.getByTestId("run-issue")).toBeDisabled();
  const issueRequest = (await h.current()).request;
  await h.controller.receipt({ environmentId: environment.id, requestId: issueRequest.id, kind: "issue", status: "done" });
  await expect(page.locator("#issue-status")).toContainText("delivered");
  h.controller.requestReview = async () => { throw new Error("Copilot review is unavailable under the current account policy"); };
  await page.getByTestId("run-review").click();
  await expect(page.locator("#error")).toContainText("account policy");
  h.controller.requestReview = async (repo, number) => h.remote.reviewRequests.push({ repo, number });
  await page.getByTestId("run-review").click();
  await expect(page.locator("#review-status")).toContainText("requested");
  await expect(page.getByTestId("run-review")).toBeDisabled();
  assert.equal(h.remote.reviewRequests.length, 1);
  const review = h.remote.pulls.find(({ number }) => number === environment.scenarios.review.number);
  h.remote.reviews = [{ user: { login: "Copilot", type: "Bot" }, commit_id: review.head.sha, submitted_at: "2026-10-06" }];
  await page.getByTestId("check-review").click();
  await expect(page.locator("#review-status")).toContainText("submitted for the current commit");
  await page.getByTestId("check-ci").click();
  await expect(page.locator("#ci-status")).toContainText("Waiting for the current PR");
  await expect(page.getByTestId("run-ci")).toBeDisabled();
  const ci = h.remote.pulls.find(({ number }) => number === environment.scenarios.ci.number);
  h.remote.ciRuns = [{ id: 71, head_sha: ci.head.sha, status: "completed", conclusion: "failure" }];
  h.remote.ciJobs = [{ name: "unit-tests", steps: [{ name: "Run unit tests", conclusion: "failure" }] }];
  await page.getByTestId("check-ci").click();
  await expect(page.getByTestId("ci-run-link")).toHaveAttribute("href", `https://github.com/${environment.repo}/actions/runs/71`);
  await expect(page.getByTestId("run-ci")).toBeEnabled();
  await page.getByTestId("run-ci").click();
  await expect(page.locator("#ci-status")).toContainText("Handoff requested");
  assert.match(h.messages[2].prompt, /open_pr_session/);
  const ciRequest = (await h.current()).request;
  await h.controller.receipt({ environmentId: environment.id, requestId: ciRequest.id, kind: "ci", status: "done" });
  h.remote.ciRuns[0].conclusion = "success";
  await page.getByTestId("check-ci").click();
  await expect(page.locator("#ci-status")).toContainText("checks are green");
  await expect(page.getByTestId("run-ci")).toBeDisabled();
  await page.reload();
  await expect(page.locator("#ci-status")).toContainText("checks are green");
  assert.equal(h.messages.length, 3);
});

test("older environments can prepare missing scenarios, while a stale provider explains why they cannot run", async (t) => {
  const h = await harness(t);
  await h.create();
  await h.link();
  const state = await h.store.read();
  delete state.environments[0].scenarios;
  delete state.environments[0].scenariosReady;
  await h.store.write(state);
  const server = await startServer(h.controller);
  t.after(server.close);
  const browser = await chromium.launch({ headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(server.url);
  await expect(page.getByTestId("run-issue")).toBeDisabled();
  await page.getByRole("button", { name: "Resume setup" }).click();
  await expect(page.getByTestId("run-issue")).toBeEnabled();
  await expect(page.getByRole("button", { name: "Resume setup" })).toBeHidden();
  assert.equal(h.remote.pulls.length, 3);
  h.controller.state = () => h.store.read();
  await page.reload();
  await expect(page.locator("#scenario-availability")).toContainText("Restart this session");
  for (const id of ["run-issue", "run-review", "run-ci", "check-review", "check-ci"]) {
    await expect(page.getByTestId(id)).toBeDisabled();
  }
  await expect(page.getByRole("button", { name: "Run feature demo" })).toBeEnabled();
});
